name: github pages

on:
  workflow_dispatch:
  issues:
    types: [opened, edited]

jobs:
  convert_issues_to_markdown_job:
      runs-on: ubuntu-latest
      name: Convert issues to markdowns.
      steps:
        - name: checkout
          uses: actions/checkout@v1
        - name: Fetch issues and generate markdowns
          uses: skyfe79/hugo-with-github-issues@v1.3
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            repo: 'blogs'
            owner: 'chajiuqqq'
            skip-author: 'bot'
            use-issue-seperator: 'true'
            output: 'content/post'
        - name: Commit files
          run: |
            git config --local user.email "chajiuqqq@gmail.com"
            git config --local user.name "chajiuqqq"
            git add .
            git commit -m "Add Posts" || echo "nothing to commit"
        - name: Push changes
          uses: ad-m/github-push-action@master
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: ${{ github.ref }}
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.117.0"
          # extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
